image: registry.access.redhat.com/ubi8/python-36

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  AWS_PROFILE: "openshift-dev"
  AWS_DOMAIN: "devcluster.openshift.com"
  AWS_SHARED_CREDENTIALS_FILE: "$CI_PROJECT_DIR/.aws/credentials"
  AWS_CONFIG_FILE: "$CI_PROJECT_DIR/.aws/config"
  CLUSTER_USER: "$GITLAB_USER_LOGIN"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install tox
  - bin/functional.sh
  - pip install -r requirements.txt
  - python setup.py develop

stages:
  - lint_and_unit_test
  - deploy
  - tier1
  - teardown

lint:
  stage: lint_and_unit_test
  script:
    - tox -e flake8

unit tests:
  stage: lint_and_unit_test
  script:
    - tox -e py36

deploy:
  stage: deploy
  script:
    - run-ci -m deployment --deploy --ocsci-conf=ocs-ci.yaml --cluster-path=cluster
  artifacts:
    when: always
    paths:
      - ocs-ci.yaml
      - cluster/
      - logs/
      - bin/oc

tier1:
  stage: tier1
  script:
    - run-ci -m tier1 --ocsci-conf=ocs-ci.yaml --cluster-path=cluster
  artifacts:
    when: always
    paths:
      - logs/

teardown:
  stage: teardown
  when: always
  script:
    - run-ci -m deployment --teardown --ocsci-conf=ocs-ci.yaml --cluster-path=cluster
  artifacts:
    when: always
    paths:
      - logs/
